# Required
version: 2

# Image to use
build:
  os: ubuntu-lts-latest
  tools:
    image: stable

# Configuration
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
