[tool.poetry]
name = "unesco-reader"
version = "0.3.1"
description = "Pythonic access to UNESCO data"
authors = ["Luca Picci <lpicci96@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.1"
tabulate = "^0.9.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
