[tool.poetry]
name = "unesco-reader"
version = "0.3.1"
description = "Pythonic access to UNESCO data"
authors = ["Luca Picci <lpicci96@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.1"
tabulate = "^0.9.0"
bs4 = "^0.0.2"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-cov = "^5.0.0"
black = "^24.3.0"
jupyter = "^1.0.0"
sphinx = "^7.2.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
