name: Enforce Black

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  run-linters:
    name: Set up linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Black
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_name: "Black formatter"
          git_email: "lpicci96@gmail.com"
          commit_message: "Fix code style issues with ${linter}"
          black: true
          auto_fix: true
